CREATE TABLE IF NOT EXISTS field10_integrated_evidence_history (
    parent_run_id TEXT NOT NULL,
    child_run_id TEXT NOT NULL,
    canonical_run_id TEXT,
    symbol TEXT NOT NULL,
    role TEXT,
    timeframe TEXT NOT NULL,
    broker_timestamp TEXT NOT NULL,
    broker_date TEXT,
    broker_hour INTEGER,
    rank INTEGER,
    current_session TEXT,
    technical_bias TEXT,
    technical_source TEXT,
    technical_reliability REAL,
    sentiment_bias TEXT,
    sentiment_source TEXT,
    sentiment_reliability REAL,
    sentiment_headline TEXT,
    sentiment_publication_time TEXT,
    sentiment_entity_match TEXT,
    session_bias TEXT,
    session_source TEXT,
    session_reliability REAL,
    regime_bias TEXT,
    regime_source TEXT,
    higher_standard_regime TEXT,
    regime_probability REAL,
    regime_entropy REAL,
    regime_posterior_margin REAL,
    expected_regime_duration REAL,
    data_mining_bias TEXT,
    data_mining_source TEXT,
    combined_evidence_bias TEXT,
    shadow_fusion_score REAL,
    evidence_available_count INTEGER,
    evidence_agreement REAL,
    conflict_index REAL,
    transition_risk_1h REAL,
    transition_risk_3h REAL,
    transition_risk_6h REAL,
    change_probability REAL,
    current_regime_run_length REAL,
    expected_stable_duration REAL,
    structural_break_status TEXT,
    drift_status TEXT,
    adaptive_window_size INTEGER,
    conformal_target_coverage REAL,
    conformal_coverage REAL,
    conformal_coverage_status TEXT,
    interval_width REAL,
    calibrated_reliability REAL,
    data_quality_grade TEXT,
    spread_quality TEXT,
    correlation_cluster TEXT,
    duplicate_exposure_penalty REAL,
    cvar_95 REAL,
    marginal_tail_risk REAL,
    suggested_risk_weight REAL,
    trade_permission TEXT,
    validation_permission TEXT,
    protected_final_action TEXT,
    outcome_settled INTEGER,
    actual_next_h1_direction TEXT,
    master_action_correct INTEGER,
    brier_score REAL,
    conditional_accuracy REAL,
    explanation TEXT,
    source_id TEXT,
    snapshot_hash TEXT NOT NULL,
    calculation_version TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (parent_run_id, symbol, timeframe, broker_timestamp, child_run_id, snapshot_hash)
);
